# Auth Service Configuration Template
# Copy this content to application.yml and modify as needed

server:
  port: ${AUTH_PORT:8081}

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_AUTH_DB:medigen_auth}?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:YOUR_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:your-secret-key-min-32-characters-long}
  expiration: ${JWT_EXPIRATION:86400000}

# REPLACE THESE WITH YOUR ACTUAL VALUES:
# - YOUR_MYSQL_PASSWORD: Your MySQL root password
# - JWT_SECRET: Generate using: openssl rand -base64 32
# Or use .env file for better security

