# Gateway Service Configuration Template
# Copy this content to application.yml and modify as needed

server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            exposedHeaders:
              - "Authorization"
              - "Content-Type"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# No database credentials needed - Gateway routes to other services

